clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: localhost
      port: 9000
      user: default
      password: ""
      threads: 1
      keepalives_idle: 0
      search_path: default
      sslmode: disable