[pytest]
log_cli = True
log_cli_level = DEBUG

filterwarnings =
    ignore:.*'soft_unicode' has been renamed to 'soft_str'*:DeprecationWarning
    ignore:.*: ResourceWarning
env_files =
    test.env
pythonpath = .
testpaths =
    tests/integration  # name per convention