
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'taxis'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'taxis'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  taxi_s3:
    bucket: 'datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi'
    fmt: 'TabSeparatedWithNames'
    structure:
      - trip_id             UInt32
      - pickup_datetime     DateTime
      - dropoff_datetime    DateTime
      - pickup_longitude    Nullable(Float64)
      - pickup_latitude     Nullable(Float64)
      - dropoff_longitude   Nullable(Float64)
      - dropoff_latitude    Nullable(Float64)
      - passenger_count     UInt8
      - trip_distance       Float32
      - fare_amount         Float32
      - extra               Float32
      - tip_amount          Float32
      - tolls_amount        Float32
      - total_amount        Float32
      - payment_type        LowCardinality(String)
      - pickup_ntaname      LowCardinality(String)
      - dropoff_ntaname     LowCardinality(String)
