---
name: "lint"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Upgrade Setuptools
        run: pip install --upgrade setuptools wheel

      - name: Install requirements
        run: |
          pip install -r dev_requirements.txt
          pip install .

      - name: Run lint
        run: make lint
