---
name: "test_matrix"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: main
  push:
    branches-ignore:
      - '*_test'
      - '*_dev'
      - '*_cloud'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} | Clickhouse ${{ matrix.clickhouse-version}} | Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      TEST_SETTINGS_FILE: latest

    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        clickhouse-version:
          - '23.8'
          - '24.1'
          - '24.2'
          - '24.3'
          - latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "DBT_CH_TEST_CH_VERSION=${{ matrix.clickhouse-version }}" >> $GITHUB_ENV

      # a fix until docker compose >v2.36.0 will be the default version in the github runner
      - name: Install Docker Compose v2.39.2
        run: |
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.39.2/docker-compose-linux-x86_64" -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          docker compose version

      - name: Run ClickHouse Cluster Containers
        env:
          PROJECT_ROOT: ${{ github.workspace }}/tests/integration
        run: REPLICA_NUM=1 docker compose -f ${{ github.workspace }}/tests/integration/docker-compose.yml up -d

      - name: Verify ClickHouse connection
        run: |
          for i in {1..15}; do docker exec integration-ch0-1 clickhouse-client --query "SELECT 1" && break || sleep 2; done

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: pip3 install -r dev_requirements.txt

      - name: Run HTTP tests
        env:
          DBT_CH_TEST_CLUSTER: test_shard
        run: |
          PYTHONPATH="${PYTHONPATH}:dbt"
          pytest tests tests/integration/adapter/basic/test_base.py --timeout=60

      - name: Run Native tests
        env:
          DBT_CH_TEST_PORT: 9000
          DBT_CH_TEST_CLUSTER: test_shard
        run: |
          PYTHONPATH="${PYTHONPATH}:dbt"
          pytest tests tests/integration/adapter/basic/test_base.py --timeout=60

      - name: Show Docker containers status
        if: always()
        run: |
          docker compose -f ${{ github.workspace }}/tests/integration/docker-compose.yml ps
          docker compose -f tests/integration/docker-compose.yml logs ch0 ch1 ch2
          docker compose -f tests/integration/docker-compose.yml exec ch0 cat /var/log/clickhouse-server/clickhouse-server.log
          docker compose -f tests/integration/docker-compose.yml exec ch1 cat /var/log/clickhouse-server/clickhouse-server.log
          docker compose -f tests/integration/docker-compose.yml exec ch2 cat /var/log/clickhouse-server/clickhouse-server.log